FROM ubuntu:16.04
MAINTAINER jperalta

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y openssh-server

RUN useradd -ms /bin/bash docker
RUN docker:docker | chpasswd

RUN service ssh restart

CMD ["/usr/sbin/sshd", "-D"]
