FROM centos:7
MAINTAINER jperalta

RUN yum update -y && yum clean all
RUN yum -y install initscripts && yum clean all
RUN yum install -y openssh-server && yum clean all

RUN useradd -ms /bin/bash docker
RUN echo docker:docker | chpasswd

RUN /usr/sbin/sshd-keygen

CMD ["/usr/sbin/sshd", "-D"]
